-- V1: Create sequences for all tables with auto-generated IDs

CREATE SEQUENCE NBP_ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_COUNTRY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_CITY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_ADDRESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_DESTINATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_ACCOMMODATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_TRANSPORT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_TRAVEL_PACKAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_APPS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_BOOKING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_DISCOUNT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_REVIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE NBP_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
