-- V2: Create all tables in FK-dependency order

-- 1. Tables with no foreign keys
CREATE TABLE NBP_ROLE (
    ID          NUMBER(19) PRIMARY KEY,
    NAME        VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE NBP_COUNTRY (
    ID          NUMBER(19) PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    CODE        VARCHAR2(10) NOT NULL UNIQUE
);

CREATE TABLE NBP_DISCOUNT (
    ID          NUMBER(19) PRIMARY KEY,
    CODE        VARCHAR2(50) NOT NULL UNIQUE,
    PERCENTAGE  NUMBER(5,2) NOT NULL CHECK (PERCENTAGE > 0 AND PERCENTAGE <= 100),
    VALID_FROM  DATE NOT NULL,
    VALID_TO    DATE NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CONSTRAINT CHK_DISCOUNT_DATES CHECK (VALID_TO >= VALID_FROM)
);

-- 2. City -> Address -> Destination
CREATE TABLE NBP_CITY (
    ID          NUMBER(19) PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    COUNTRY_ID  NUMBER(19) NOT NULL,
    CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES NBP_COUNTRY(ID)
);

CREATE TABLE NBP_ADDRESS (
    ID          NUMBER(19) PRIMARY KEY,
    STREET      VARCHAR2(200) NOT NULL,
    ZIP_CODE    VARCHAR2(20),
    CITY_ID     NUMBER(19) NOT NULL,
    CONSTRAINT FK_ADDRESS_CITY FOREIGN KEY (CITY_ID) REFERENCES NBP_CITY(ID)
);

CREATE TABLE NBP_DESTINATION (
    ID          NUMBER(19) PRIMARY KEY,
    NAME        VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    IMAGE_URL   VARCHAR2(500),
    CITY_ID     NUMBER(19) NOT NULL,
    CONSTRAINT FK_DESTINATION_CITY FOREIGN KEY (CITY_ID) REFERENCES NBP_CITY(ID)
);

-- 3. User and Apps
CREATE TABLE NBP_USER (
    ID           NUMBER(19) PRIMARY KEY,
    FIRST_NAME   VARCHAR2(100) NOT NULL,
    LAST_NAME    VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(200) NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(200) NOT NULL,
    USERNAME     VARCHAR2(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(30),
    BIRTH_DATE   DATE,
    ADDRESS_ID   NUMBER(19),
    ROLE_ID      NUMBER(19) NOT NULL,
    CONSTRAINT FK_USER_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES NBP_ADDRESS(ID),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES NBP_ROLE(ID)
);

CREATE TABLE NBP_APPS (
    ID          NUMBER(19) PRIMARY KEY,
    APP_ID      VARCHAR2(100) NOT NULL UNIQUE,
    MANAGER_ID  NUMBER(19),
    EXPIRY_DATE DATE
);

-- 4. Accommodation, Transport, Travel Package
CREATE TABLE NBP_ACCOMMODATION (
    ID              NUMBER(19) PRIMARY KEY,
    NAME            VARCHAR2(200) NOT NULL,
    TYPE            VARCHAR2(50) NOT NULL CHECK (TYPE IN ('HOTEL', 'HOSTEL', 'APARTMENT', 'VILLA', 'RESORT')),
    STARS           NUMBER(1) CHECK (STARS BETWEEN 1 AND 5),
    PHONE           VARCHAR2(30),
    EMAIL           VARCHAR2(200),
    PRICE_PER_NIGHT NUMBER(10,2) NOT NULL CHECK (PRICE_PER_NIGHT > 0),
    CAPACITY        NUMBER(10) NOT NULL CHECK (CAPACITY > 0),
    ADDRESS_ID      NUMBER(19) NOT NULL,
    DESTINATION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT FK_ACCOMMODATION_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES NBP_ADDRESS(ID),
    CONSTRAINT FK_ACCOMMODATION_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES NBP_DESTINATION(ID)
);

CREATE TABLE NBP_TRANSPORT (
    ID              NUMBER(19) PRIMARY KEY,
    TYPE            VARCHAR2(50) NOT NULL CHECK (TYPE IN ('FLIGHT', 'BUS', 'TRAIN', 'FERRY', 'CAR_RENTAL')),
    PROVIDER        VARCHAR2(200) NOT NULL,
    DEPARTURE_DATE  DATE NOT NULL,
    ARRIVAL_DATE    DATE NOT NULL,
    ORIGIN          VARCHAR2(200) NOT NULL,
    PRICE           NUMBER(10,2) NOT NULL CHECK (PRICE > 0),
    CAPACITY        NUMBER(10) NOT NULL CHECK (CAPACITY > 0),
    DESTINATION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT FK_TRANSPORT_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES NBP_DESTINATION(ID),
    CONSTRAINT CHK_TRANSPORT_DATES CHECK (ARRIVAL_DATE >= DEPARTURE_DATE)
);

CREATE TABLE NBP_TRAVEL_PACKAGE (
    ID              NUMBER(19) PRIMARY KEY,
    NAME            VARCHAR2(200) NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    BASE_PRICE      NUMBER(10,2) NOT NULL CHECK (BASE_PRICE > 0),
    MAX_CAPACITY    NUMBER(10) NOT NULL CHECK (MAX_CAPACITY > 0),
    START_DATE      DATE NOT NULL,
    END_DATE        DATE NOT NULL,
    DESTINATION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT FK_PACKAGE_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES NBP_DESTINATION(ID),
    CONSTRAINT CHK_PACKAGE_DATES CHECK (END_DATE >= START_DATE)
);

-- 5. Junction tables (composite PKs)
CREATE TABLE NBP_PACKAGE_TRANSPORT (
    TRAVEL_PACKAGE_ID NUMBER(19) NOT NULL,
    TRANSPORT_ID      NUMBER(19) NOT NULL,
    TRANSPORT_ROLE    VARCHAR2(20) NOT NULL CHECK (TRANSPORT_ROLE IN ('OUTBOUND', 'RETURN', 'INTERNAL')),
    SEQUENCE_ORDER    NUMBER(5) NOT NULL,
    CONSTRAINT PK_PACKAGE_TRANSPORT PRIMARY KEY (TRAVEL_PACKAGE_ID, TRANSPORT_ID),
    CONSTRAINT FK_PKG_TRANSPORT_PACKAGE FOREIGN KEY (TRAVEL_PACKAGE_ID) REFERENCES NBP_TRAVEL_PACKAGE(ID),
    CONSTRAINT FK_PKG_TRANSPORT_TRANSPORT FOREIGN KEY (TRANSPORT_ID) REFERENCES NBP_TRANSPORT(ID)
);

CREATE TABLE NBP_PACKAGE_ACCOMMODATION (
    TRAVEL_PACKAGE_ID NUMBER(19) NOT NULL,
    ACCOMMODATION_ID  NUMBER(19) NOT NULL,
    CHECK_IN          DATE NOT NULL,
    CHECK_OUT         DATE NOT NULL,
    NIGHTS            NUMBER(5) NOT NULL CHECK (NIGHTS > 0),
    CONSTRAINT PK_PACKAGE_ACCOMMODATION PRIMARY KEY (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID),
    CONSTRAINT FK_PKG_ACCOM_PACKAGE FOREIGN KEY (TRAVEL_PACKAGE_ID) REFERENCES NBP_TRAVEL_PACKAGE(ID),
    CONSTRAINT FK_PKG_ACCOM_ACCOMMODATION FOREIGN KEY (ACCOMMODATION_ID) REFERENCES NBP_ACCOMMODATION(ID),
    CONSTRAINT CHK_PKG_ACCOM_DATES CHECK (CHECK_OUT > CHECK_IN)
);

-- 6. Booking, Payment, Review
CREATE TABLE NBP_BOOKING (
    ID                 NUMBER(19) PRIMARY KEY,
    USER_ID            NUMBER(19) NOT NULL,
    BOOKING_TYPE       VARCHAR2(20) NOT NULL CHECK (BOOKING_TYPE IN ('TRAVEL_PACKAGE', 'ACCOMMODATION', 'TRANSPORT')),
    BOOKING_DATE       DATE DEFAULT SYSDATE NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    TOTAL_PRICE        NUMBER(10,2) NOT NULL CHECK (TOTAL_PRICE >= 0),
    TRAVEL_PACKAGE_ID  NUMBER(19),
    ACCOMMODATION_ID   NUMBER(19),
    TRANSPORT_ID       NUMBER(19),
    CONSTRAINT FK_BOOKING_USER FOREIGN KEY (USER_ID) REFERENCES NBP_USER(ID),
    CONSTRAINT FK_BOOKING_PACKAGE FOREIGN KEY (TRAVEL_PACKAGE_ID) REFERENCES NBP_TRAVEL_PACKAGE(ID),
    CONSTRAINT FK_BOOKING_ACCOMMODATION FOREIGN KEY (ACCOMMODATION_ID) REFERENCES NBP_ACCOMMODATION(ID),
    CONSTRAINT FK_BOOKING_TRANSPORT FOREIGN KEY (TRANSPORT_ID) REFERENCES NBP_TRANSPORT(ID)
);

CREATE TABLE NBP_PAYMENT (
    ID              NUMBER(19) PRIMARY KEY,
    BOOKING_ID      NUMBER(19) NOT NULL UNIQUE,
    DISCOUNT_ID     NUMBER(19),
    AMOUNT          NUMBER(10,2) NOT NULL CHECK (AMOUNT >= 0),
    DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0 NOT NULL CHECK (DISCOUNT_AMOUNT >= 0),
    FINAL_AMOUNT    NUMBER(10,2) NOT NULL CHECK (FINAL_AMOUNT >= 0),
    PAYMENT_DATE    DATE DEFAULT SYSDATE NOT NULL,
    METHOD          VARCHAR2(30) NOT NULL CHECK (METHOD IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER')),
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    CONSTRAINT FK_PAYMENT_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES NBP_BOOKING(ID),
    CONSTRAINT FK_PAYMENT_DISCOUNT FOREIGN KEY (DISCOUNT_ID) REFERENCES NBP_DISCOUNT(ID)
);

CREATE TABLE NBP_REVIEW (
    ID          NUMBER(19) PRIMARY KEY,
    USER_ID     NUMBER(19) NOT NULL,
    BOOKING_ID  NUMBER(19) NOT NULL,
    RATING      NUMBER(1) NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    COMMENT_TEXT VARCHAR2(2000),
    REVIEW_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_REVIEW_USER FOREIGN KEY (USER_ID) REFERENCES NBP_USER(ID),
    CONSTRAINT FK_REVIEW_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES NBP_BOOKING(ID)
);

-- 7. Audit log
CREATE TABLE NBP_LOG (
    ID          NUMBER(19) PRIMARY KEY,
    ACTION_NAME VARCHAR2(20) NOT NULL,
    TABLE_NAME  VARCHAR2(100) NOT NULL,
    DATE_TIME   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DB_USER     VARCHAR2(100) NOT NULL
);
