-- V3: Create auto-ID triggers and audit log triggers

-- =============================================
-- AUTO-ID TRIGGERS (assign sequence NEXTVAL on INSERT)
-- =============================================

CREATE OR REPLACE TRIGGER NBP_ROLE_BI
BEFORE INSERT ON NBP_ROLE FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_ROLE_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_COUNTRY_BI
BEFORE INSERT ON NBP_COUNTRY FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_COUNTRY_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_CITY_BI
BEFORE INSERT ON NBP_CITY FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_CITY_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_ADDRESS_BI
BEFORE INSERT ON NBP_ADDRESS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_ADDRESS_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_DESTINATION_BI
BEFORE INSERT ON NBP_DESTINATION FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_DESTINATION_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_ACCOMMODATION_BI
BEFORE INSERT ON NBP_ACCOMMODATION FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_ACCOMMODATION_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_TRANSPORT_BI
BEFORE INSERT ON NBP_TRANSPORT FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_TRANSPORT_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_TRAVEL_PACKAGE_BI
BEFORE INSERT ON NBP_TRAVEL_PACKAGE FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_USER_BI
BEFORE INSERT ON NBP_USER FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_USER_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_APPS_BI
BEFORE INSERT ON NBP_APPS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_APPS_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_BOOKING_BI
BEFORE INSERT ON NBP_BOOKING FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_BOOKING_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_DISCOUNT_BI
BEFORE INSERT ON NBP_DISCOUNT FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_DISCOUNT_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_PAYMENT_BI
BEFORE INSERT ON NBP_PAYMENT FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_PAYMENT_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_REVIEW_BI
BEFORE INSERT ON NBP_REVIEW FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_REVIEW_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NBP_LOG_BI
BEFORE INSERT ON NBP_LOG FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := NBP_LOG_SEQ.NEXTVAL;
    END IF;
END;
/

-- =============================================
-- AUDIT LOG TRIGGERS (log INSERT/UPDATE/DELETE to NBP_LOG)
-- =============================================

CREATE OR REPLACE TRIGGER NBP_ROLE_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_ROLE
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_ROLE', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_COUNTRY_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_COUNTRY
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_COUNTRY', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_CITY_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_CITY
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_CITY', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_ADDRESS_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_ADDRESS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_ADDRESS', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_DESTINATION_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_DESTINATION
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_DESTINATION', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_ACCOMMODATION_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_ACCOMMODATION
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_ACCOMMODATION', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_TRANSPORT_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_TRANSPORT
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_TRANSPORT', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_TRAVEL_PACKAGE_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_TRAVEL_PACKAGE
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_TRAVEL_PACKAGE', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_USER_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_USER
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_USER', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_APPS_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_APPS
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_APPS', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_BOOKING_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_BOOKING
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_BOOKING', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_DISCOUNT_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_DISCOUNT
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_DISCOUNT', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_PAYMENT_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_PAYMENT
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_PAYMENT', SYSTIMESTAMP, USER);
END;
/

CREATE OR REPLACE TRIGGER NBP_REVIEW_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON NBP_REVIEW
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF INSERTING THEN v_action := 'INSERT';
    ELSIF UPDATING THEN v_action := 'UPDATE';
    ELSE v_action := 'DELETE';
    END IF;
    INSERT INTO NBP_LOG (ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
    VALUES (NBP_LOG_SEQ.NEXTVAL, v_action, 'NBP_REVIEW', SYSTIMESTAMP, USER);
END;
/
