-- V4: Seed reference data

-- Roles
INSERT INTO NBP_ROLE (ID, NAME) VALUES (NBP_ROLE_SEQ.NEXTVAL, 'ADMIN');
INSERT INTO NBP_ROLE (ID, NAME) VALUES (NBP_ROLE_SEQ.NEXTVAL, 'AGENT');
INSERT INTO NBP_ROLE (ID, NAME) VALUES (NBP_ROLE_SEQ.NEXTVAL, 'USER');

-- Countries
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Bosna i Hercegovina', 'BA');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Hrvatska', 'HR');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Turska', 'TR');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Egipat', 'EG');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Njemacka', 'DE');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Italija', 'IT');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Grcka', 'GR');
INSERT INTO NBP_COUNTRY (ID, NAME, CODE) VALUES (NBP_COUNTRY_SEQ.NEXTVAL, 'Spanija', 'ES');

-- Cities (using subqueries to reference country IDs)
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Sarajevo', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'BA'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Mostar', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'BA'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Dubrovnik', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'HR'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Zagreb', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'HR'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Istanbul', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'TR'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Antalya', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'TR'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Kairo', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'EG'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Berlin', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'DE'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Rim', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'IT'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Atina', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'GR'));
INSERT INTO NBP_CITY (ID, NAME, COUNTRY_ID) VALUES (NBP_CITY_SEQ.NEXTVAL, 'Barcelona', (SELECT ID FROM NBP_COUNTRY WHERE CODE = 'ES'));

-- Admin user (password: admin123 - BCrypt hashed)
INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Admin', 'NBP', 'admin@nbp.ba',
        '$2a$12$LJ3m4sFQm/J.E0K4B4M4QOZmEHY8WMJqNJ8VVwOKhLjKRpOmXxKaG',
        'admin', '+38761000000', TO_DATE('1990-01-01', 'YYYY-MM-DD'), NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'ADMIN'));
