-- V5: Extended seed data (10+ rows per table)

-- =============================================
-- ADDRESSES
-- =============================================
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Titova 1', '71000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Sarajevo'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Marsala Tita 22', '71000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Sarajevo'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Kralja Tomislava 5', '88000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Mostar'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Stradun 10', '20000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Dubrovnik'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Ilica 15', '10000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Zagreb'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Istiklal Caddesi 100', '34000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Istanbul'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Ataturk Bulvari 50', '07000', (SELECT ID FROM NBP_CITY WHERE NAME = 'Antalya'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Pyramids Road 1', '12511', (SELECT ID FROM NBP_CITY WHERE NAME = 'Kairo'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Unter den Linden 5', '10117', (SELECT ID FROM NBP_CITY WHERE NAME = 'Berlin'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Via Veneto 20', '00187', (SELECT ID FROM NBP_CITY WHERE NAME = 'Rim'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Ermou 8', '10563', (SELECT ID FROM NBP_CITY WHERE NAME = 'Atina'));
INSERT INTO NBP_ADDRESS (ID, STREET, ZIP_CODE, CITY_ID) VALUES (NBP_ADDRESS_SEQ.NEXTVAL, 'Las Ramblas 45', '08002', (SELECT ID FROM NBP_CITY WHERE NAME = 'Barcelona'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Amir', 'Hodzic', 'amir.agent@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'amir.agent', '+38761111001', TO_DATE('1985-03-15', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Titova 1'),
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'AGENT'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Lejla', 'Pasic', 'lejla.agent@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'lejla.agent', '+38762111002', TO_DATE('1990-07-22', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Marsala Tita 22'),
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'AGENT'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Muhamed', 'Kovac', 'muhamed@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'muhamed.k', '+38761222001', TO_DATE('1995-01-10', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Kralja Tomislava 5'),
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Sara', 'Begic', 'sara@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'sara.b', '+38762222002', TO_DATE('1998-05-20', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Stradun 10'),
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Damir', 'Zukic', 'damir@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'damir.z', '+38761333001', TO_DATE('1992-11-08', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Ilica 15'),
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Amina', 'Selimovic', 'amina@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'amina.s', '+38762333002', TO_DATE('2000-03-25', 'YYYY-MM-DD'),
        NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Emir', 'Hadzimuratovic', 'emir@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'emir.h', '+38761444001', TO_DATE('1993-08-14', 'YYYY-MM-DD'),
        NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Nermina', 'Bajric', 'nermina@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'nermina.b', '+38762444002', TO_DATE('1997-12-03', 'YYYY-MM-DD'),
        NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Jasmin', 'Tahirovic', 'jasmin@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'jasmin.t', '+38761555001', TO_DATE('1988-06-17', 'YYYY-MM-DD'),
        NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

INSERT INTO NBP_USER (ID, FIRST_NAME, LAST_NAME, EMAIL, "PASSWORD", USERNAME, PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
VALUES (NBP_USER_SEQ.NEXTVAL, 'Belma', 'Ibrahimovic', 'belma@nbp.ba',
        '$2a$12$nZ2EbUr3Rjj50Uo5zUZOMeHyupz7w/k8CgOPuxNGHfweF4bIdaSMS',
        'belma.i', '+38762555002', TO_DATE('2001-09-30', 'YYYY-MM-DD'),
        NULL,
        (SELECT ID FROM NBP_ROLE WHERE NAME = 'USER'));

-- =============================================
-- DESTINATIONS
-- =============================================
INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Stari grad Sarajevo', 'Historijsko srediste Sarajeva sa carsijom i dzamijama', 'https://example.com/sarajevo.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Sarajevo'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Vrelo Bosne', 'Prirodni park na izvoru rijeke Bosne', 'https://example.com/vrelo.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Sarajevo'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Stari most Mostar', 'Ikonicki osmanski most iz 16. vijeka', 'https://example.com/mostar.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Mostar'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Stari grad Dubrovnik', 'UNESCO zasticeni stari grad okruzen zidinama', 'https://example.com/dubrovnik.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Dubrovnik'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Plitvicka jezera', 'Nacionalni park sa kaskadnim jezerima', 'https://example.com/plitvice.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Zagreb'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Topkapi palata', 'Historijska palata osmanskih sultana', 'https://example.com/topkapi.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Istanbul'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Antalya plaza', 'Luksuzne plaze i resorti na Mediteranu', 'https://example.com/antalya.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Antalya'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Piramide u Gizi', 'Drevne egipatske piramide i Sfinga', 'https://example.com/piramide.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Kairo'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Berlinski zid', 'Historijsko mjesto Berlinskog zida', 'https://example.com/berlin.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Berlin'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Koloseum Rim', 'Anticko rimsko amfiteatro', 'https://example.com/rim.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Rim'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Akropola Atina', 'Drevna grcka citadela sa Partenonom', 'https://example.com/atina.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Atina'));

INSERT INTO NBP_DESTINATION (ID, NAME, DESCRIPTION, IMAGE_URL, CITY_ID)
VALUES (NBP_DESTINATION_SEQ.NEXTVAL, 'Sagrada Familia', 'Gaudiova nedovrsena remek-djelo katedrala', 'https://example.com/barcelona.jpg', (SELECT ID FROM NBP_CITY WHERE NAME = 'Barcelona'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Europe Sarajevo', 'HOTEL', 5, '+38733276600', 'info@hoteleurope.ba', 150, 100,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Titova 1'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Sarajevo'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hostel City Center', 'HOSTEL', 2, '+38733201100', 'info@hostelcc.ba', 25, 50,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Marsala Tita 22'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Sarajevo'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Bristol Mostar', 'HOTEL', 4, '+38736500100', 'info@hotelbristol.ba', 80, 60,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Kralja Tomislava 5'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari most Mostar'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Excelsior Dubrovnik', 'HOTEL', 5, '+38520353353', 'info@excelsior.hr', 300, 80,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Stradun 10'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Esplanade Zagreb', 'HOTEL', 5, '+38514566666', 'info@esplanade.hr', 200, 120,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Ilica 15'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Plitvicka jezera'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Four Seasons Istanbul', 'HOTEL', 5, '+902122381000', 'info@fourseasons.tr', 400, 150,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Istiklal Caddesi 100'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Topkapi palata'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Rixos Premium Antalya', 'RESORT', 5, '+902423100000', 'info@rixos.tr', 250, 200,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Ataturk Bulvari 50'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Antalya plaza'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Marriott Mena House Kairo', 'HOTEL', 5, '+20237371111', 'info@marriott.eg', 180, 100,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Pyramids Road 1'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Piramide u Gizi'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Adlon Berlin', 'HOTEL', 5, '+4930226110', 'info@adlon.de', 350, 90,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Unter den Linden 5'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Berlinski zid'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Eden Roma', 'HOTEL', 5, '+39064781201', 'info@hotelroma.it', 280, 70,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Via Veneto 20'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Koloseum Rim'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'Hotel Grande Bretagne Atina', 'HOTEL', 5, '+302103330000', 'info@grandebretagne.gr', 220, 80,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Ermou 8'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Akropola Atina'));

INSERT INTO NBP_ACCOMMODATION (ID, NAME, TYPE, STARS, PHONE, EMAIL, PRICE_PER_NIGHT, CAPACITY, ADDRESS_ID, DESTINATION_ID)
VALUES (NBP_ACCOMMODATION_SEQ.NEXTVAL, 'W Barcelona', 'HOTEL', 5, '+34932952800', 'info@wbarcelona.es', 320, 110,
        (SELECT ID FROM NBP_ADDRESS WHERE STREET = 'Las Ramblas 45'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Sagrada Familia'));

-- =============================================
-- TRANSPORTS
-- =============================================
INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Bosnia Air', TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-06-01', 'YYYY-MM-DD'), 'Sarajevo', 120, 180,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'BUS', 'Centrotrans', TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-06-01', 'YYYY-MM-DD'), 'Sarajevo', 25, 50,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari most Mostar'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Turkish Airlines', TO_DATE('2026-06-05', 'YYYY-MM-DD'), TO_DATE('2026-06-05', 'YYYY-MM-DD'), 'Sarajevo', 220, 200,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Topkapi palata'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Turkish Airlines', TO_DATE('2026-06-12', 'YYYY-MM-DD'), TO_DATE('2026-06-12', 'YYYY-MM-DD'), 'Istanbul', 180, 200,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Antalya plaza'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'EgyptAir', TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 'Sarajevo', 350, 160,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Piramide u Gizi'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Lufthansa', TO_DATE('2026-07-10', 'YYYY-MM-DD'), TO_DATE('2026-07-10', 'YYYY-MM-DD'), 'Sarajevo', 280, 180,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Berlinski zid'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Alitalia', TO_DATE('2026-07-15', 'YYYY-MM-DD'), TO_DATE('2026-07-15', 'YYYY-MM-DD'), 'Sarajevo', 260, 160,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Koloseum Rim'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Aegean Airlines', TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-01', 'YYYY-MM-DD'), 'Sarajevo', 230, 140,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Akropola Atina'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Iberia', TO_DATE('2026-08-10', 'YYYY-MM-DD'), TO_DATE('2026-08-10', 'YYYY-MM-DD'), 'Sarajevo', 310, 170,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Sagrada Familia'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'BUS', 'FlixBus', TO_DATE('2026-06-15', 'YYYY-MM-DD'), TO_DATE('2026-06-15', 'YYYY-MM-DD'), 'Zagreb', 40, 60,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Plitvicka jezera'));

INSERT INTO NBP_TRANSPORT (ID, TYPE, PROVIDER, DEPARTURE_DATE, ARRIVAL_DATE, ORIGIN, PRICE, CAPACITY, DESTINATION_ID)
VALUES (NBP_TRANSPORT_SEQ.NEXTVAL, 'FLIGHT', 'Croatia Airlines', TO_DATE('2026-06-20', 'YYYY-MM-DD'), TO_DATE('2026-06-20', 'YYYY-MM-DD'), 'Sarajevo', 140, 120,
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik'));

-- =============================================
-- TRAVEL PACKAGES
-- =============================================
INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Sarajevo City Break', '3 dana u srcu Bosne, obilazak Bascarsi je i okolice', 299, 20,
        TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-06-03', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Sarajevo'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Dubrovnik Ljetovanje', '7 dana na Jadranu, obilazak starog grada', 899, 15,
        TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-07', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Istanbul Orijentaln o putovanje', '5 dana u Istanbulu, istorija i kultura', 749, 25,
        TO_DATE('2026-06-05', 'YYYY-MM-DD'), TO_DATE('2026-06-09', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Topkapi palata'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Egipat Piramide Tour', '8 dana, Kairo i piramide u Gizi', 1299, 20,
        TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-08', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Piramide u Gizi'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Rim Vjecni grad', '4 dana u Rimu, Vatikan i Koloseum', 799, 18,
        TO_DATE('2026-07-15', 'YYYY-MM-DD'), TO_DATE('2026-07-18', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Koloseum Rim'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Atina i Grcka', '6 dana u Atini i posjet Acropolisu', 849, 22,
        TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-06', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Akropola Atina'));

INSERT INTO NBP_TRAVEL_PACKAGE (ID, NAME, DESCRIPTION, BASE_PRICE, MAX_CAPACITY, START_DATE, END_DATE, DESTINATION_ID)
VALUES (NBP_TRAVEL_PACKAGE_SEQ.NEXTVAL, 'Barcelona Fiesta', '5 dana u Barceloni, Gaudi i plaze', 999, 20,
        TO_DATE('2026-08-10', 'YYYY-MM-DD'), TO_DATE('2026-08-14', 'YYYY-MM-DD'),
        (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Sagrada Familia'));

-- =============================================
-- PACKAGE TRANSPORT LINKS
-- =============================================
INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Dubrovnik Ljetovanje'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Bosnia Air' AND DESTINATION_ID = (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik')),
        'OUTBOUND', 1);

INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Istanbul Orijentaln o putovanje'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Turkish Airlines' AND DEPARTURE_DATE = TO_DATE('2026-06-05', 'YYYY-MM-DD')),
        'OUTBOUND', 1);

INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Egipat Piramide Tour'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'EgyptAir'),
        'OUTBOUND', 1);

INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Rim Vjecni grad'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Alitalia'),
        'OUTBOUND', 1);

INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Atina i Grcka'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Aegean Airlines'),
        'OUTBOUND', 1);

INSERT INTO NBP_PACKAGE_TRANSPORT (TRAVEL_PACKAGE_ID, TRANSPORT_ID, TRANSPORT_ROLE, SEQUENCE_ORDER)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Barcelona Fiesta'),
        (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Iberia'),
        'OUTBOUND', 1);

-- =============================================
-- PACKAGE ACCOMMODATION LINKS
-- =============================================
INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Sarajevo City Break'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Europe Sarajevo'),
        TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-06-03', 'YYYY-MM-DD'), 2);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Dubrovnik Ljetovanje'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Excelsior Dubrovnik'),
        TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-07', 'YYYY-MM-DD'), 6);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Istanbul Orijentaln o putovanje'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Four Seasons Istanbul'),
        TO_DATE('2026-06-05', 'YYYY-MM-DD'), TO_DATE('2026-06-09', 'YYYY-MM-DD'), 4);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Egipat Piramide Tour'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Marriott Mena House Kairo'),
        TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-08', 'YYYY-MM-DD'), 7);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Rim Vjecni grad'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Eden Roma'),
        TO_DATE('2026-07-15', 'YYYY-MM-DD'), TO_DATE('2026-07-18', 'YYYY-MM-DD'), 3);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Atina i Grcka'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Grande Bretagne Atina'),
        TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-06', 'YYYY-MM-DD'), 5);

INSERT INTO NBP_PACKAGE_ACCOMMODATION (TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, CHECK_IN, CHECK_OUT, NIGHTS)
VALUES ((SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Barcelona Fiesta'),
        (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'W Barcelona'),
        TO_DATE('2026-08-10', 'YYYY-MM-DD'), TO_DATE('2026-08-14', 'YYYY-MM-DD'), 4);
§11
INSERT INTO NBP_DISCOUNT (ID, CODE, PERCENTAGE, VALID_FROM, VALID_TO, DESCRIPTION)
VALUES (NBP_DISCOUNT_SEQ.NEXTVAL, 'SUMMER2026', 10, TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-08-31', 'YYYY-MM-DD'), 'Ljetni popust 10%');

INSERT INTO NBP_DISCOUNT (ID, CODE, PERCENTAGE, VALID_FROM, VALID_TO, DESCRIPTION)
VALUES (NBP_DISCOUNT_SEQ.NEXTVAL, 'WELCOME15', 15, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), 'Dobrodosli popust za nove korisnike');

INSERT INTO NBP_DISCOUNT (ID, CODE, PERCENTAGE, VALID_FROM, VALID_TO, DESCRIPTION)
VALUES (NBP_DISCOUNT_SEQ.NEXTVAL, 'NBP20', 20, TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-05-31', 'YYYY-MM-DD'), 'Proljecna akcija 20%');

INSERT INTO NBP_DISCOUNT (ID, CODE, PERCENTAGE, VALID_FROM, VALID_TO, DESCRIPTION)
VALUES (NBP_DISCOUNT_SEQ.NEXTVAL, 'EARLY10', 10, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-04-30', 'YYYY-MM-DD'), 'Early bird popust');

INSERT INTO NBP_DISCOUNT (ID, CODE, PERCENTAGE, VALID_FROM, VALID_TO, DESCRIPTION)
VALUES (NBP_DISCOUNT_SEQ.NEXTVAL, 'VIP25', 25, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), 'VIP klijenti - ekskluzivni popust');

-- =============================================
-- BOOKINGS
-- =============================================
INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'muhamed.k'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-01', 'YYYY-MM-DD'), 'CONFIRMED', 299,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Sarajevo City Break'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-05', 'YYYY-MM-DD'), 'CONFIRMED', 899,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Dubrovnik Ljetovanje'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'damir.z'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'CONFIRMED', 749,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Istanbul Orijentaln o putovanje'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'amina.s'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-12', 'YYYY-MM-DD'), 'CONFIRMED', 1299,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Egipat Piramide Tour'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'emir.h'),
        'ACCOMMODATION', TO_DATE('2026-04-15', 'YYYY-MM-DD'), 'CONFIRMED', 150,
        NULL, (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Europe Sarajevo'), NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'nermina.b'),
        'TRANSPORT', TO_DATE('2026-04-18', 'YYYY-MM-DD'), 'CONFIRMED', 120,
        NULL, NULL, (SELECT ID FROM NBP_TRANSPORT WHERE PROVIDER = 'Bosnia Air' AND DESTINATION_ID = (SELECT ID FROM NBP_DESTINATION WHERE NAME = 'Stari grad Dubrovnik')));

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'jasmin.t'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-20', 'YYYY-MM-DD'), 'PENDING', 799,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Rim Vjecni grad'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'belma.i'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-22', 'YYYY-MM-DD'), 'PENDING', 849,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Atina i Grcka'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'muhamed.k'),
        'TRAVEL_PACKAGE', TO_DATE('2026-04-25', 'YYYY-MM-DD'), 'CANCELLED', 999,
        (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Barcelona Fiesta'), NULL, NULL);

INSERT INTO NBP_BOOKING (ID, USER_ID, BOOKING_TYPE, BOOKING_DATE, STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
VALUES (NBP_BOOKING_SEQ.NEXTVAL, (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b'),
        'ACCOMMODATION', TO_DATE('2026-04-28', 'YYYY-MM-DD'), 'CONFIRMED', 80,
        NULL, (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Bristol Mostar'), NULL);

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'muhamed.k') AND TRAVEL_PACKAGE_ID = (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Sarajevo City Break')),
        NULL, 299, 0, 299, TO_DATE('2026-04-01', 'YYYY-MM-DD'), 'CREDIT_CARD', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b') AND TRAVEL_PACKAGE_ID = (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Dubrovnik Ljetovanje')),
        (SELECT ID FROM NBP_DISCOUNT WHERE CODE = 'SUMMER2026'),
        899, 89.9, 809.1, TO_DATE('2026-04-05', 'YYYY-MM-DD'), 'CREDIT_CARD', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'damir.z') AND BOOKING_TYPE = 'TRAVEL_PACKAGE'),
        (SELECT ID FROM NBP_DISCOUNT WHERE CODE = 'WELCOME15'),
        749, 112.35, 636.65, TO_DATE('2026-04-10', 'YYYY-MM-DD'), 'PAYPAL', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'amina.s') AND BOOKING_TYPE = 'TRAVEL_PACKAGE'),
        NULL, 1299, 0, 1299, TO_DATE('2026-04-12', 'YYYY-MM-DD'), 'BANK_TRANSFER', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'emir.h') AND BOOKING_TYPE = 'ACCOMMODATION'),
        NULL, 150, 0, 150, TO_DATE('2026-04-15', 'YYYY-MM-DD'), 'DEBIT_CARD', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'nermina.b') AND BOOKING_TYPE = 'TRANSPORT'),
        (SELECT ID FROM NBP_DISCOUNT WHERE CODE = 'VIP25'),
        120, 30, 90, TO_DATE('2026-04-18', 'YYYY-MM-DD'), 'CREDIT_CARD', 'COMPLETED');

INSERT INTO NBP_PAYMENT (ID, BOOKING_ID, DISCOUNT_ID, AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
VALUES (NBP_PAYMENT_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b') AND ACCOMMODATION_ID = (SELECT ID FROM NBP_ACCOMMODATION WHERE NAME = 'Hotel Bristol Mostar')),
        NULL, 80, 0, 80, TO_DATE('2026-04-28', 'YYYY-MM-DD'), 'CREDIT_CARD', 'COMPLETED');

-- =============================================
-- REVIEWS (only for CONFIRMED bookings)
-- =============================================
INSERT INTO NBP_REVIEW (ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
VALUES (NBP_REVIEW_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_USER WHERE USERNAME = 'muhamed.k'),
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'muhamed.k') AND TRAVEL_PACKAGE_ID = (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Sarajevo City Break')),
        5, 'Odlicno iskustvo, preporucujem svima!', TO_DATE('2026-06-04', 'YYYY-MM-DD'));

INSERT INTO NBP_REVIEW (ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
VALUES (NBP_REVIEW_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b'),
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'sara.b') AND TRAVEL_PACKAGE_ID = (SELECT ID FROM NBP_TRAVEL_PACKAGE WHERE NAME = 'Dubrovnik Ljetovanje')),
        5, 'Dubrovnik je nevjerovatan grad, hotel bio fantastican!', TO_DATE('2026-07-08', 'YYYY-MM-DD'));

INSERT INTO NBP_REVIEW (ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
VALUES (NBP_REVIEW_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_USER WHERE USERNAME = 'damir.z'),
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'damir.z') AND BOOKING_TYPE = 'TRAVEL_PACKAGE'),
        4, 'Istanbul je fascinantan, ali transport mogao biti bolji.', TO_DATE('2026-06-10', 'YYYY-MM-DD'));

INSERT INTO NBP_REVIEW (ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
VALUES (NBP_REVIEW_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_USER WHERE USERNAME = 'amina.s'),
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'amina.s') AND BOOKING_TYPE = 'TRAVEL_PACKAGE'),
        5, 'Egipat je san koji sam ostvarila. Preporuka 10/10!', TO_DATE('2026-07-09', 'YYYY-MM-DD'));

INSERT INTO NBP_REVIEW (ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
VALUES (NBP_REVIEW_SEQ.NEXTVAL,
        (SELECT ID FROM NBP_USER WHERE USERNAME = 'emir.h'),
        (SELECT ID FROM NBP_BOOKING WHERE USER_ID = (SELECT ID FROM NBP_USER WHERE USERNAME = 'emir.h') AND BOOKING_TYPE = 'ACCOMMODATION'),
        4, 'Hotel Europe je prelijep, usluga na visokom nivou.', TO_DATE('2026-04-20', 'YYYY-MM-DD'));

INSERT INTO NBP_APPS (ID, APP_ID, MANAGER_ID, EXPIRY_DATE)
VALUES (NBP_APPS_SEQ.NEXTVAL, 'NBP-APP-001', NULL, TO_DATE('2027-01-01', 'YYYY-MM-DD'));

INSERT INTO NBP_APPS (ID, APP_ID, MANAGER_ID, EXPIRY_DATE)
VALUES (NBP_APPS_SEQ.NEXTVAL, 'NBP-APP-002', NULL, TO_DATE('2027-06-30', 'YYYY-MM-DD'));

INSERT INTO NBP_APPS (ID, APP_ID, MANAGER_ID, EXPIRY_DATE)
VALUES (NBP_APPS_SEQ.NEXTVAL, 'NBP-APP-003', NULL, TO_DATE('2026-12-31', 'YYYY-MM-DD'));