-- Booking documents stored in DB (no external blob storage)

CREATE SEQUENCE NBP_BOOKING_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE NBP_BOOKING_DOCUMENT (
    ID            NUMBER(19) PRIMARY KEY,
    BOOKING_ID    NUMBER(19) NOT NULL,
    DOC_TYPE      VARCHAR2(20) NOT NULL CHECK (DOC_TYPE IN ('RECEIPT', 'VOUCHER')),
    FILENAME      VARCHAR2(255) NOT NULL,
    CONTENT_TYPE  VARCHAR2(100) NOT NULL,
    CONTENT       BLOB NOT NULL,
    SIZE_BYTES    NUMBER(19),
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_BDOC_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES NBP_BOOKING(ID),
    CONSTRAINT UQ_BDOC_BOOKING_TYPE UNIQUE (BOOKING_ID, DOC_TYPE)
);

