-- V8: Backup tables and scheduled backup job for critical tables

CREATE TABLE NBP_USER_BACKUP (
    BACKUP_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID           NUMBER(19),
    FIRST_NAME   VARCHAR2(100),
    LAST_NAME    VARCHAR2(100),
    EMAIL        VARCHAR2(200),
    USERNAME     VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(30),
    BIRTH_DATE   DATE,
    ADDRESS_ID   NUMBER(19),
    ROLE_ID      NUMBER(19)
);

CREATE TABLE NBP_BOOKING_BACKUP (
    BACKUP_DATE       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID                NUMBER(19),
    USER_ID           NUMBER(19),
    BOOKING_TYPE      VARCHAR2(20),
    BOOKING_DATE      DATE,
    STATUS            VARCHAR2(20),
    TOTAL_PRICE       NUMBER(10,2),
    TRAVEL_PACKAGE_ID NUMBER(19),
    ACCOMMODATION_ID  NUMBER(19),
    TRANSPORT_ID      NUMBER(19)
);

CREATE TABLE NBP_PAYMENT_BACKUP (
    BACKUP_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID              NUMBER(19),
    BOOKING_ID      NUMBER(19),
    DISCOUNT_ID     NUMBER(19),
    AMOUNT          NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    FINAL_AMOUNT    NUMBER(10,2),
    PAYMENT_DATE    DATE,
    METHOD          VARCHAR2(30),
    STATUS          VARCHAR2(20)
);

CREATE TABLE NBP_REVIEW_BACKUP (
    BACKUP_DATE  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ID           NUMBER(19),
    USER_ID      NUMBER(19),
    BOOKING_ID   NUMBER(19),
    RATING       NUMBER(1),
    COMMENT_TEXT VARCHAR2(2000),
    REVIEW_DATE  DATE
);

CREATE OR REPLACE PROCEDURE NBP_BACKUP_CRITICAL_TABLES AS
BEGIN
    DELETE FROM NBP_USER_BACKUP    WHERE BACKUP_DATE < SYSTIMESTAMP - INTERVAL '7' DAY;
    DELETE FROM NBP_BOOKING_BACKUP WHERE BACKUP_DATE < SYSTIMESTAMP - INTERVAL '7' DAY;
    DELETE FROM NBP_PAYMENT_BACKUP WHERE BACKUP_DATE < SYSTIMESTAMP - INTERVAL '7' DAY;
    DELETE FROM NBP_REVIEW_BACKUP  WHERE BACKUP_DATE < SYSTIMESTAMP - INTERVAL '7' DAY;

    INSERT INTO NBP_USER_BACKUP (BACKUP_DATE, ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME,
                                  PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID)
    SELECT SYSTIMESTAMP, ID, FIRST_NAME, LAST_NAME, EMAIL, USERNAME,
           PHONE_NUMBER, BIRTH_DATE, ADDRESS_ID, ROLE_ID
    FROM NBP_USER;

    INSERT INTO NBP_BOOKING_BACKUP (BACKUP_DATE, ID, USER_ID, BOOKING_TYPE, BOOKING_DATE,
                                     STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID)
    SELECT SYSTIMESTAMP, ID, USER_ID, BOOKING_TYPE, BOOKING_DATE,
           STATUS, TOTAL_PRICE, TRAVEL_PACKAGE_ID, ACCOMMODATION_ID, TRANSPORT_ID
    FROM NBP_BOOKING;

    INSERT INTO NBP_PAYMENT_BACKUP (BACKUP_DATE, ID, BOOKING_ID, DISCOUNT_ID, AMOUNT,
                                     DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS)
    SELECT SYSTIMESTAMP, ID, BOOKING_ID, DISCOUNT_ID, AMOUNT,
           DISCOUNT_AMOUNT, FINAL_AMOUNT, PAYMENT_DATE, METHOD, STATUS
    FROM NBP_PAYMENT;

    INSERT INTO NBP_REVIEW_BACKUP (BACKUP_DATE, ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE)
    SELECT SYSTIMESTAMP, ID, USER_ID, BOOKING_ID, RATING, COMMENT_TEXT, REVIEW_DATE
    FROM NBP_REVIEW;

    COMMIT;
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'NBP_DAILY_BACKUP_JOB',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'NBPT4.NBP_BACKUP_CRITICAL_TABLES',
        start_date      => TRUNC(SYSDATE + 1),
        repeat_interval => 'FREQ=DAILY; BYHOUR=0; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Daily midnight backup of critical NBP tables'
    );
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    NBP_BACKUP_CRITICAL_TABLES;
END;
/
